add: chain_id param in etherscan query req
foundry-rs/block-explorers pull request #36
Opened 2024-03-27 21:05 UTC by yash-atreya

Required for foundry-rs/foundry#7485

2024-03-27 21:12 UTC, mattsse requested changes
hmm, do all the other endpoints now also support the chain id or just verification?

I think this only covers verification:

https://docs.etherscan.io/contract-verification/multichain-verification

so I think we should limit this pr to verify

2024-03-27 21:32 UTC, yash-atreya commented
> hmm, do all the other endpoints now also support the chain id or just verification?
> 
> I think this only covers verification:
> 
> https://docs.etherscan.io/contract-verification/multichain-verification
> 
> so I think we should limit this pr to verify

I could just append `chain_id` to `other` in verify related methods in https://github.com/foundry-rs/block-explorers/blob/main/src/verify.rs

2024-03-29 12:06 UTC, mattsse commented
we can add this as optional arg to the verify args

```rust 
#[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<bool>,
```

2024-03-29 16:37 UTC, mattsse requested changes
great!
a few more nits

2024-03-29 16:37 UTC, mattsse commented on src/lib.rs
> +        chain_id: Option<u64>,
this argument is redundant because we already have it on self.

2024-03-29 16:37 UTC, mattsse commented on src/lib.rs
> +    pub fn with_chain_id(mut self, chain_id: u64) -> Self {
This should accept `Chain`
we also need a getter for this

2024-03-29 16:37 UTC, mattsse commented on src/lib.rs
> +    /// Configures the chain id for etherscan verification
let's link to etherscan multichain verification docs

2024-03-29 16:37 UTC, mattsse commented on src/lib.rs
> +        self.with_chain_id(chain.id()).with_api_url(etherscan_api_url?)?.with_url(etherscan_url?)
we need to add a note to function docs that this also sets the chain id for multichain verification

2024-03-29 18:28 UTC, mattsse approved these changes
lgtm, I believe this should do it

2024-03-29 18:31 UTC, merged